{% set version = '1.0-0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-roi.plugin.glpk
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ROI.plugin.glpk_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ROI.plugin.glpk/ROI.plugin.glpk_{{ version }}.tar.gz
  sha256: b361b0d4222d74b21432cdc6990762affecdbcec8fd6bbdb13b78b59cb04b444

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-roi >=0.3_0
    - r-rglpk >=0.6_2
  run:
    - r-base
    - r-roi >=0.3_0
    - r-rglpk >=0.6_2

test:
  commands:
    - $R -e "library('ROI.plugin.glpk')"           # [not win]
    - "\"%R%\" -e \"library('ROI.plugin.glpk')\""  # [win]

about:
  home: http://roi.r-forge.r-project.org/, https://r-forge.r-project.org/projects/roi/
  license: GPL-3.0-only
  summary: Enhances the 'R' Optimization Infrastructure ('ROI') package by registering the free
    'GLPK' solver. It allows for solving mixed integer linear programming ('MILP') problems
    as well as all variants/combinations of 'LP', 'IP'.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - janjagusch


# Package: ROI.plugin.glpk
# Version: 1.0-0
# Title: 'ROI' Plug-in 'GLPK'
# Authors@R: c(person("Stefan", "Theussl", role = c("aut", "cre"), email = "Stefan.Theussl@R-Project.org"))
# Description: Enhances the 'R' Optimization Infrastructure ('ROI') package by registering the free 'GLPK' solver. It allows for solving mixed integer linear programming ('MILP') problems as well as all variants/combinations of 'LP', 'IP'.
# Imports: methods, ROI (>= 0.3-0), Rglpk (>= 0.6-2)
# License: GPL-3
# URL: http://roi.r-forge.r-project.org/, https://r-forge.r-project.org/projects/roi/
# NeedsCompilation: no
# Packaged: 2020-08-29 16:34:23 UTC; f
# Author: Stefan Theussl [aut, cre]
# Maintainer: Stefan Theussl <Stefan.Theussl@R-Project.org>
# Repository: CRAN
# Date/Publication: 2020-08-30 07:30:03 UTC
